development:
  user_name: quydoantran@gmail.com
  password: plmokn123
  authentication: :plain
  domain: eseb.com
  address: smtp.gmail.com
  port: 587
  tls: true
test: &test
  user_name: exampleran@gmail.com
  password: password
  authentication: :plain
  domain: eseb.com
  address: smtp.gmail.com
  port: 587
  tls: true

cucumber:
  <<: *test

production:
  user_name: no-reply@snember.com
  password: minority
  address: 202.43.44.96
  port: 25
